### ISSUE TITLE
文档笔误提示

### ISSUE THREAD

**Issue by liujibin** [flutter-dev/website#43]
文档[编写第一个 Flutter 应用](http://doc.flutter-dev.cn/get-started/codelab/)页，第三步添加有状态的widget下面文案有问题。见图![](https://i.imgur.com/uo9A2PM.png)英文文档2)也有同样问题![](https://i.imgur.com/U8WuS8O.png)

**Comment by MelonRice** [comment]
@ZhangQinglian @liujibin 已经调整
